[[constraint]]
  name = "github.com/sirupsen/logrus"
  version ="1.4.2"


[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"


[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.2"
